# Generated by Django 5.2.7 on 2025-10-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_discount_alter_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='length',
            new_name='length_type',
        ),
    ]
